### ISSUE TITLE
"Comparison method violates its general contract" in VisitorLogic.sweepCache

### ISSUE THREAD

**Issue by kno10** [sweble/osr-common#1]
```
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeLo(ComparableTimSort.java:744)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:481)
        at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:406)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
        at java.util.Arrays.sort(Arrays.java:1312)
        at de.fau.cs.osr.utils.visitor.VisitorLogic.sweepCache(VisitorLogic.java:225)
        at de.fau.cs.osr.utils.visitor.VisitorLogic.findVisit(VisitorLogic.java:205)
        at de.fau.cs.osr.utils.visitor.VisitorLogic.resolveAndVisit(VisitorLogic.java:105)
```

This is caused by multiple threads changing the `lastUse` while one thread is sorting. The synchronization on `sweepCache` is not enough to prevent other threads from changing `lastUse`. It may be enough to just attempt to partially sort the targets to identify the least frequently used, rather than calling `Arrays.sort`. A quick select strategy may be worth trying. (Note: this bug likely doesn't appear in older Java versions, which did not use TimSort).

A workaround for Java 8 is to do
```
System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");
```

Migrated from https://github.com/sweble/sweble-wikitext/issues/49

**Comment by hannesd** [comment]
Fixed in version 2.2.0
